apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
data:
  EUREKA_URI: http://service-registry:8761/eureka
  CONFIG_SERVER_URI: http://config-server:8888
  KAFKA_SERVERS: kafka:9092
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  ELASTICSEARCH_HOST: elasticsearch
  ELASTICSEARCH_PORT: "9200"
  ZIPKIN_BASE_URL: http://zipkin:9411
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  DB_USERNAME: postgres
