{{- if .Values.orderService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
spec:
  replicas: {{ .Values.orderService.replicaCount }}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      initContainers:
        {{- include "ecommerce.waitForPort" (dict "name" "postgres-order" "host" "postgres-order" "port" "5432") | nindent 8 }}
        {{- include "ecommerce.waitForHealth" (dict "name" "config-server" "url" "http://config-server:8888/actuator/health") | nindent 8 }}
      containers:
        - name: order-service
          image: {{ include "ecommerce.image" (dict "repo" .Values.orderService.image.repository "tag" .Values.orderService.image.tag "global" .Values.global) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 8084
          env:
            - name: CONFIG_SERVER_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CONFIG_SERVER_URI
            - name: EUREKA_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: EUREKA_URI
            - name: KAFKA_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_SERVERS
            - name: DB_HOST
              value: postgres-order
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: order_db
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
          resources:
            {{- toYaml .Values.orderService.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 80
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 8084
      targetPort: 8084
{{- end }}
