{{- if .Values.paymentService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: payment-service
spec:
  replicas: {{ .Values.paymentService.replicaCount }}
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      initContainers:
        {{- include "ecommerce.waitForPort" (dict "name" "postgres-payment" "host" "postgres-payment" "port" "5432") | nindent 8 }}
      containers:
        - name: payment-service
          image: {{ include "ecommerce.image" (dict "repo" .Values.paymentService.image.repository "tag" .Values.paymentService.image.tag "global" .Values.global) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
          resources:
            {{- toYaml .Values.paymentService.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 80
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: 8085
      targetPort: 8085
{{- end }}
