apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.secrets.dbPassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  mail-username: {{ .Values.secrets.mail.username | quote }}
  mail-password: {{ .Values.secrets.mail.password | quote }}
