{{- if .Values.userService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: user-service
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        {{- include "ecommerce.waitForPort" (dict "name" "postgres-user" "host" "postgres-user" "port" "5432") | nindent 8 }}
        {{- include "ecommerce.waitForHealth" (dict "name" "config-server" "url" "http://config-server:8888/actuator/health") | nindent 8 }}
      containers:
        - name: user-service
          image: {{ include "ecommerce.image" (dict "repo" .Values.userService.image.repository "tag" .Values.userService.image.tag "global" .Values.global) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 8081
          env:
            - name: CONFIG_SERVER_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CONFIG_SERVER_URI
            - name: EUREKA_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: EUREKA_URI
            - name: KAFKA_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_SERVERS
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST
            - name: DB_HOST
              value: postgres-user
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: user_db
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
          resources:
            {{- toYaml .Values.userService.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 80
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8081
      targetPort: 8081
{{- end }}
