{{- if .Values.zipkin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: {{ .Values.zipkin.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 9411
          resources:
            {{- toYaml .Values.zipkin.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 30
            periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: zipkin
spec:
  selector:
    app: zipkin
  ports:
    - port: 9411
      targetPort: 9411
{{- end }}
