apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ecommerce
type: Opaque
stringData:
  password: postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: ecommerce
type: Opaque
stringData:
  jwt-secret: myVerySecretKeyForDevelopmentPurposesOnly1234567890
  mail-username: your-email@gmail.com
  mail-password: your-mail-app-password
