apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  # Namespace & shared config
  - 00-namespace.yaml
  - 01-secrets.yaml
  - 02-configmap.yaml

  # Infrastructure - stateful
  - infrastructure/postgres-user.yaml
  - infrastructure/postgres-product.yaml
  - infrastructure/postgres-inventory.yaml
  - infrastructure/postgres-order.yaml
  - infrastructure/postgres-payment.yaml
  - infrastructure/kafka.yaml
  - infrastructure/redis.yaml
  - infrastructure/elasticsearch.yaml

  # Infrastructure - stateless
  - infrastructure/zipkin.yaml
  - infrastructure/prometheus-configmap.yaml
  - infrastructure/prometheus.yaml
  - infrastructure/grafana.yaml

  # Application services
  - services/service-registry.yaml
  - services/config-server.yaml
  - services/api-gateway.yaml
  - services/user-service.yaml
  - services/product-service.yaml
  - services/inventory-service.yaml
  - services/order-service.yaml
  - services/payment-service.yaml
  - services/notification-service.yaml
  - services/search-service.yaml
  - services/frontend.yaml
